/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CategoryIndexRouteImport } from './routes/$category.index'
import { Route as ArticleCreateRouteImport } from './routes/article/create'
import { Route as CategorySlugRouteImport } from './routes/$category.$slug'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoryIndexRoute = CategoryIndexRouteImport.update({
  id: '/$category/',
  path: '/$category/',
  getParentRoute: () => rootRouteImport,
} as any)
const ArticleCreateRoute = ArticleCreateRouteImport.update({
  id: '/article/create',
  path: '/article/create',
  getParentRoute: () => rootRouteImport,
} as any)
const CategorySlugRoute = CategorySlugRouteImport.update({
  id: '/$category/$slug',
  path: '/$category/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/$category/$slug': typeof CategorySlugRoute
  '/article/create': typeof ArticleCreateRoute
  '/$category/': typeof CategoryIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/$category/$slug': typeof CategorySlugRoute
  '/article/create': typeof ArticleCreateRoute
  '/$category': typeof CategoryIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/$category/$slug': typeof CategorySlugRoute
  '/article/create': typeof ArticleCreateRoute
  '/$category/': typeof CategoryIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/$category/$slug'
    | '/article/create'
    | '/$category/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/login' | '/$category/$slug' | '/article/create' | '/$category'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/$category/$slug'
    | '/article/create'
    | '/$category/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  CategorySlugRoute: typeof CategorySlugRoute
  ArticleCreateRoute: typeof ArticleCreateRoute
  CategoryIndexRoute: typeof CategoryIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$category/': {
      id: '/$category/'
      path: '/$category'
      fullPath: '/$category/'
      preLoaderRoute: typeof CategoryIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/article/create': {
      id: '/article/create'
      path: '/article/create'
      fullPath: '/article/create'
      preLoaderRoute: typeof ArticleCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$category/$slug': {
      id: '/$category/$slug'
      path: '/$category/$slug'
      fullPath: '/$category/$slug'
      preLoaderRoute: typeof CategorySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  CategorySlugRoute: CategorySlugRoute,
  ArticleCreateRoute: ArticleCreateRoute,
  CategoryIndexRoute: CategoryIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
